Refactor: renamed config file variables; minor refactors (tidy up details)

diff --git a/toot b/toot
--- a/toot
+++ b/toot
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # set -u
-set -eo pipefail
+# set -eo pipefail
 
 # ========== Tootils ==========
 #
@@ -19,9 +19,10 @@ set -eo pipefail
 declare op=$1
 shift
 
+declare SYSTEM HERE
 #shellcheck disable=SC2034
 declare -A conf
-declare SYSTEM HERE config_dir config_file config_file_backup
+declare file_dir file_conf file_conf_backup
 
 # ===== Essential functions =====
 
@@ -36,8 +37,8 @@ fatal() {
 }
 
 fatal-assert() {
-    erro " - Fatal Assertion Failure (bug):"
-    fatal "$*"
+    erro "  Fatal Assertion Failure (bug):"
+    fatal "    $*"
 }
 
 #shellcheck disable=SC1090
@@ -84,30 +85,30 @@ elif [[ $SYSTEM == 'win' ]]; then
     XDG_CONFIG_HOME=$(cygpath -u "$XDG_CONFIG_HOME")
 fi
 
-config_dir="$XDG_CONFIG_HOME/tootils"
-config_file="$config_dir/tootils.conf"
-config_file_backup="$config_dir/backup.conf"
+file_dir="$XDG_CONFIG_HOME/tootils"
+file_conf="$file_dir/tootils.conf"
+file_conf_backup="$file_dir/backup.conf"
 
 # this could be improved as it looks the dirtiest of all hehe
 # oh, I know, I'll make a `tootils.conf.template` and copy its data
-if [[ ! -f $config_file ]]; then
-    mkdir -p "$config_dir"
-    touch "$config_file"
-    (( $? )) && fatal "Could not create configuration file at location: $config_file"
+if [[ ! -f $file_conf ]]; then
+    mkdir -p "$file_dir"
+    touch "$file_conf"
+    (( $? )) && fatal "Could not create configuration file at location: $file_conf"
 
-    echo -e "# Tootils fresh config\n# Comment lines start with #\n# Fill the following required entries:\n\nbackup_root=\n" > "$config_file"
+    echo -e "# Tootils fresh config\n# Comment lines start with #\n# Fill the following required entries:\n\nbackup_root=\n" > "$file_conf"
 
-    echo "Configuration file created at location: $config_file"
+    echo "Configuration file created at location: $file_conf"
     echo "Please set it up with your desired values and relaunch Tootils."
     exit 0
 fi
 # hastily written. might be fine though
-if [[ ! -f $config_file_backup ]]; then
-    touch "$config_file_backup"
-    (( $? )) && fatal "Could not create configuration file at location: $config_file_backup"
+if [[ ! -f $file_conf_backup ]]; then
+    touch "$file_conf_backup"
+    (( $? )) && fatal "Could not create configuration file at location: $file_conf_backup"
 fi
 
-load-config "conf" "backup_root" "" < "$config_file"
+load-config "conf" "backup_root" "" < "$file_conf"
 
 # Print the title
 echo " ${C_RED_B_BL}-Tootils-${C_RESET}"
